### ISSUE TITLE
cant use tenorcap 

### ISSUE THREAD

**Issue by afasdfsfdsagddafh** [reticivis-net/mediaforge#173]
pyvips.error.Error: Command raised an exception: Error: unable to call gaussmat
  gaussmat: parameter sigma not set
[traceback.txt](https://github.com/HexCodeFFF/mediaforge/files/11471518/traceback.txt)

**Comment by HexCodeFFF** [comment]
I'm unable to reproduce this. Can you send the image and command that reliably reproduce this error?
