### ISSUE TITLE
ffmpeg: corrupted size vs. prev_size in fastbins

### ISSUE THREAD

**Issue by Caseyyyyyyyyy** [reticivis-net/mediaforge#192]
[traceback.txt](https://github.com/HexCodeFFF/mediaforge/files/12189343/traceback.txt)

**Comment by HexCodeFFF** [comment]
> corrupted size vs. prev_size in fastbins
Ffmpeg what the fuck

**Comment by reticivis-net** [comment]
this is #147 why did i not do that
