### ISSUE TITLE
Custom Commands: -filter_complex_script

### ISSUE THREAD

**Issue by g-l-i-t-c-h-o-r-s-e** [reticivis-net/mediaforge#194]
### Describe the feature you'd like

There is an FFMpeg command called `-filter_complex_script` that allows you to make and use custom filterchains read from a file. This would allow users to have the option to really make filters and memes to the their specific needs, and give a mobile solution for FFMpeg and video editing as well.

in practice, the command would be something like: <br> `ffmpeg -i input1.mp4 -i input2.mp4 -filter_complex_script FilterFile.txt -map "[final]" -map 0 -crf 20 -shortest output.mp4 -y`

the file `FilterFile.txt` would contain something like:
```
[0]scale=640x360[v1];[1]scale=640x360[v2];[v1]invert[v1];[v2]hflip[v2;][v1][v2]hstack[final]
```

**Comment by reticivis-net** [comment]
I'm worried about giving people unfiltered access to ffmpeg, I'm not sure that's safe and could lead to DoS attacks, plus its such a niche case that I think it'd just be easier to use ffmpeg on your local machine
