### ISSUE TITLE
Sony Vegas Support?

### ISSUE THREAD

**Issue by Jamieisbest** [reticivis-net/mediaforge#206]
### Describe the feature you'd like

Like gradient map, Shining stars, etc.

### Is your feature request related to a problem? Please describe.

I wondering if It'd cause any problems of some sort.

### Describe alternatives you've considered

AVS4YOU support too?

### Anything Else

If there is any problems just notify me

**Comment by HexCodeFFF** [comment]
Wdym Sony Vegas support? Like opening Sony Vegas files? That’d be a problem for FFMmeg to solve, not me

**Comment by Jamieisbest** [comment]
> Wdym Sony Vegas support? Like opening Sony Vegas files? That’d be a problem for FFMmeg to solve, not me

No I mean the FX EFFECTS to have

**Comment by HexCodeFFF** [comment]
Ah
I feel this is a very niche use case that would take a lot of work, especially if ffmpeg doesn’t just have the given effect. I also don’t want nor do I think it’s possible for MediaForge to programmatically interact with Sony Vegas  anyways

**Comment by Jamieisbest** [comment]
At least make some more commands at least
