### ISSUE TITLE
Command 'videodl' raised an exception: NonBugError: Cannot fit video into Discord.

### ISSUE THREAD

**Issue by ForgetheMedia** [reticivis-net/mediaforge#223]
### Describe the bug

I wanted to glitch the video I uploaded and an error occurred...

### Traceback

[traceback.txt](https://github.com/reticivis-net/mediaforge/files/13627795/traceback.txt)

### Expected Behavior

I wanted it to say video uploaded...

**Comment by ForgetheMedia** [comment]
HELP!!!!

**Comment by reticivis-net** [comment]
not a bug. the video is too large to fit in discord's upload limit.
