### ISSUE TITLE
Command 'speechbubble' raised an exception:

### ISSUE THREAD

**Issue by Yournormaluser** [reticivis-net/mediaforge#224]
### Describe the bug

Half of the commands don't work.

### Traceback

[traceback.txt](https://github.com/reticivis-net/mediaforge/files/13708901/traceback.txt)

### Expected Behavior

Add a speechbubble to an image.

### Steps To Reproduce

Post media, use command, get an error

**Comment by reticivis-net** [comment]
fixed
