### ISSUE TITLE
Command ('ffprobe', '-v', 'panic', '-count_packets', '-show_entries', 'stream=codec_type,codec_name,nb_read_packets', '-print_format', 'json', '/dev/shm/mediaforge/aWjxSbUKdRog.mhtml') failed.

### ISSUE THREAD

**Issue by MegaloKlept** [reticivis-net/mediaforge#227]
### Describe the bug

I'm just trying to download a vid to share with friends and this thing decided to quit on me.

### Traceback

[traceback.txt](https://github.com/reticivis-net/mediaforge/files/13883217/traceback.txt)

### Expected Behavior

I just wanted a youtube video to download

### Steps To Reproduce

!videodl https://youtu.be/4BHtQQh8dLo?si=ZmXGfV3RVEI46yn_

**Comment by reticivis-net** [comment]
likely related to the underlying error of #209 ?

**Comment by MegaloKlept** [comment]
> likely related to the underlying error of #209 ?

Idk dude. I just wanna download vids, I ain't as smart as everyone else on here ;-;

**Comment by reticivis-net** [comment]
> > likely related to the underlying error of #209 ?
> 
> Idk dude. I just wanna download vids, I ain't as smart as everyone else on here ;-;

Just thinking out loud as to what's causing it. Not your fault, i need to investigate it.

**Comment by reticivis-net** [comment]
i just noticed its a fucking .mhtml file? what the hell even is that? closing since I don't think that's a valid media format
