### ISSUE TITLE
Command ('ffmpeg', '-i', '/dev/shm/mediaforge/CjFYMyuf.mp4', '-gifflags', '-transdiff', '-vf', "fps=fps='min(source_fps,50)',split[s0][s1];[s0]palettegen=reserve_transparent=1[p];[s1][p]paletteuse=bayer", '-fps_mode', 'vfr', '/dev/shm/mediaforge/WMVLuNFR.gif') failed.

### ISSUE THREAD

**Issue by 3boodhly** [reticivis-net/mediaforge#228]
### Describe the bug

. 

### Traceback

.. 

### Expected Behavior

Sometimes Error 

### Steps To Reproduce

$togif error

### Anything Else

![Screenshot_٢٠٢٤٠١٢٣_٢٢٢٧١٤_Discord](https://github.com/reticivis-net/mediaforge/assets/157529856/fbc2a33c-62c6-4fa6-a981-a48952bcc80a)

**Comment by reticivis-net** [comment]
Please upload the attached traceback (and fill out the form properly next time)
