### ISSUE TITLE
ffmpeg: Nothing was written into output file, because at least one of its streams received no packets.

### ISSUE THREAD

**Issue by 3boodhly** [reticivis-net/mediaforge#229]
### Describe the bug

I can't fix this problem but i try bro... 

### Traceback

[traceback (1).txt](https://github.com/reticivis-net/mediaforge/files/14099065/traceback.1.txt)

### Expected Behavior

I was expecting that the robot would send an Uploading and send the video in gif format. I hope you fix this problem...

### Steps To Reproduce

1. I send video with command in one massge 
2. And the bot send me the gif.. 

### Anything Else

![Screenshot_٢٠٢٤٠١٣٠_١٦٣٨٣٩_Discord](https://github.com/reticivis-net/mediaforge/assets/157529856/69cc634f-d115-4b51-8676-aff4c49e0069)

**Comment by reticivis-net** [comment]
i might have fixed this. reopen if there are issues

**Comment by imthaghost** [comment]
> i might have fixed this. reopen if there are issues

How was this fixed?

**Comment by reticivis-net** [comment]
> > i might have fixed this. reopen if there are issues
> 
> 
> 
> How was this fixed?
> 
> 

Iirc it gives this issue if the input is empty
