### ISSUE TITLE
Command "help editing" results in error

### ISSUE THREAD

**Issue by MasterAnimit** [reticivis-net/mediaforge#230]
### Describe the bug

:eemark: discord.app_commands.errors.CommandInvokeError: Hybrid command raised an error: Command 'help' raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In data.embeds.0.fields: Must be 25 or fewer in length. 

### Traceback

[traceback.txt](https://github.com/reticivis-net/mediaforge/files/14219793/traceback.txt) - from /help

[traceback (1).txt](https://github.com/reticivis-net/mediaforge/files/14219795/traceback.1.txt) - from $help

### Expected Behavior

Bot sends an answer with basic command descriptions of comments of "Editing" section

### Steps To Reproduce

0.1.  (if using diresct message) Open private conv with MediaForge 
1. By command:
1.1 Type /help 
1.2 Choose "inquiry"
1.3 Type "editing"
2. By plain text:
2.1 Type "$help editing"

### Anything Else

Other 4 options here works well, no matter if / or $ is used

![image](https://github.com/reticivis-net/mediaforge/assets/77850598/86693e81-1d68-464c-9ed3-9b1ddf81d8e9)

**Comment by reticivis-net** [comment]
closed in https://github.com/reticivis-net/mediaforge/commit/651ef723932713e5767eaff69b1788edd1a68d19
