### ISSUE TITLE
Command 'speechbubble' raised an exception: FileNotFoundError: [Errno 2] No such file or directory: '/dev/shm/mediaforge/hhlrMifJ.png'

### ISSUE THREAD

**Issue by 1zwy** [reticivis-net/mediaforge#238]
### Describe the bug

Shi idk, adding speechbubble to gif

### Traceback

[traceback.txt](https://github.com/reticivis-net/mediaforge/files/14751784/traceback.txt)

**Comment by palaceswitcher** [comment]
This is also an issue with other image formats, such as PNG and JPG.

**Comment by reticivis-net** [comment]
i *think* i fixed this. reopen if it still happens
