### ISSUE TITLE
im trying to trim a video but its not working

### ISSUE THREAD

**Issue by chickenbutt1** [reticivis-net/mediaforge#240]
### Describe the bug

the application just doesnt respond

### Traceback

no traceback

### Expected Behavior

it was supposed to like trim the video

### Steps To Reproduce

https://cdn.discordapp.com/attachments/1128478850322550784/1223517767894827028/jrANgdhOPtjJ.mp4?ex=661a24b7&is=6607afb7&hm=25058180c64657e456b70f8edac148378e9a72bd1cf5b2fb46908cc86642390e&
try and trim to 129 seconds

### Anything Else

🦞🦞🦞🦞😼😼😼😼

**Comment by reticivis-net** [comment]
seems to work now. closing, reopen if it isn't fixed
