### ISSUE TITLE
Command 'caption' raised an exception: CMDError: Command ('ffmpeg', '-i', '/dev/shm/mediaforge/ZrMKtMSY.png', '-i', '/dev/shm/mediaforge/prdyAGzM.gif', '-filter_complex', '[0]format=pix_fmts=yuva420p[0f];[1]format=pix_fmts=yuva420p[1f];[0f][1f]vstack=inputs=2', '-c:v', 'png', '-fs', '1G', '-fps_mode', 'vfr', '/dev/shm/mediaforge/oRWYHRtD.mp4') failed.

### ISSUE THREAD

**Issue by telaphone99** [reticivis-net/mediaforge#241]
### Describe the bug

??? i genuinely don't fucking know it just won't work

### Traceback

[traceback.txt](https://github.com/reticivis-net/mediaforge/files/14919844/traceback.txt)

### Expected Behavior

it to work

### Steps To Reproduce

1. send a gif
2. /caption
3. profit

**Comment by reticivis-net** [comment]
seems to work now. closing, reopen if it isn't fixed

**Comment by reticivis-net** [comment]
wait wrong issue

**Comment by reticivis-net** [comment]
my guess is that it's #147
