### ISSUE TITLE
Command 'caption' raised an exception: CMDError: Command ('ffmpeg', '-i', '/dev/shm/mediaforge/lvMqtxxZ.png', '-i', '/dev/shm/mediaforge/FxLoZfRI.gif', '-filter_complex', '[0]format=pix_fmts=yuva420p[0f];[1]format=pix_fmts=yuva420p[1f];[0f][1f]vstack=inputs=2', '-c:v', 'png', '-fs', '1G', '-fps_mode', 'vfr', '/dev/shm/mediaforge/zpTeabAr.mp4') failed.

### ISSUE THREAD

**Issue by linuxelite69** [reticivis-net/mediaforge#248]
### Describe the bug

it supposed to add caption thingy but it give error 

### Traceback

[traceback.txt](https://github.com/user-attachments/files/16243499/traceback.txt)

### Expected Behavior

media was supposed to have caption thingy on it

### Steps To Reproduce

1. send a gif
2. use /caption command
3. watch a cunfuzling error come up for no reason
4. question if the cia is watching me
5. go commit warcrimes

### Anything Else

it didnt make a cheeseburger appear out of nowhere so area 51 aliens arent involoved luckily

**Comment by reticivis-net** [comment]
its #147
