### ISSUE TITLE
Bot missing “read channel history” perms gives cryptic error

### ISSUE THREAD

**Issue by JoshKellyIsLying** [reticivis-net/mediaforge#264]
### Describe the bug

giving a 403 error

### Traceback

[traceback.txt](https://github.com/user-attachments/files/17387948/traceback.txt)

### Expected Behavior

give me what i want

### Steps To Reproduce

do any command. (that needs to use a image)
get error

**Comment by reticivis-net** [comment]
The bot needs message history perms if you don’t provide it with media in the command itself. I should add a better error message but this isn’t a bug

**Comment by JoshKellyIsLying** [comment]
haven't seen this but thanks
