### ISSUE TITLE
libx264 "requested bitrate is too low" in 2 pass encoding

### ISSUE THREAD

**Issue by QueenXRaider** [reticivis-net/mediaforge#70]
improcessing.CMDError: Command raised an exception: CMDError: Command ('ffmpeg', '-i', 'temp/PExCdRLOXcFD.mp4', '-c:v', 'h264', '-b:v', '3214.7809520756855', '-pass', '2', '-passlogfile', 'temp/oeRGSFKh.log', '-c:a', 'aac', '-b:a', '128000', '-f', 'mp4', 'temp/copfcMeN.mp4') failed.

[traceback.txt](https://github.com/HexCodeFFF/mediaforge/files/8162755/traceback.txt)

**Comment by HexCodeFFF** [comment]
Can you upload the traceback file?

**Comment by QueenXRaider** [comment]
> Can you upload the traceback file?

yeah my bad, i just updated the traceback file

**Comment by HexCodeFFF** [comment]
Alright I see what's going on now. Should be fixed soon

**Comment by QueenXRaider** [comment]
alr, thanks :)

**Comment by HexCodeFFF** [comment]
I'll close it when I fix it otherwise im going to forget

**Comment by HexCodeFFF** [comment]
ok this is not as simple as i thought
this is an issue in the x264 library which ffmpeg uses. the critical line is [right here](https://github.com/mirror/x264/blob/0bb85e8bbc85244d5c8fd300033ca32539b541b7/encoder/ratecontrol.c#L2934-L2939). i understand how `all_available_bits` is calculated, but `all_const_bits` is calculated from `misc_bits` which I don't quite understand. if anyone understands where this comes from, i'd love to hear it

**Comment by HexCodeFFF** [comment]
for anyone following this issue, this issue occurs when your video is so big that when mediaforge attempts to fit it into discord ffmpeg freaks out so try not to do that

**Comment by reticivis-net** [comment]
closing in favor of #251
