### ISSUE TITLE
add support for 50mb/100mb file size limit in boosted servers

### ISSUE THREAD

**Issue by ZeNyfh** [reticivis-net/mediaforge#71]
The issue is that the bot is limited to 8mb, even with servers with the 50mb/100mb boost perk which then makes the bot do some compressing down to under 8mb

It would be nice to see support for this as it is quite annoying to just have a video compressed when in theory it could be sent by the bot in the guild.

The only issues that this could cause are longer upload times which could not be the best, but it is still a feature request to consider.

**Comment by HexCodeFFF** [comment]
this is something i've considered before, but since the bot runs on a computer in my basement, that extra bandwidth would be _my_ bandwidth. currently, i'm not a huge fan of that
however, i should add it as a config option for those hosting it themselves or for future use.

**Comment by PortalRex** [comment]
@HexCodeFFF bump on this as I do host the bot myself and it would be extremely useful to have. Alternatively I could just up the max file size limit but I am unsure how the error processing would be for files over the limit.

**Comment by HexCodeFFF** [comment]
If you want a quick workaround, I believe the global maximum file size is a config setting. Change it from ~8 million to 50 or 100 mil

**Comment by PortalRex** [comment]
Would it downsize or error out on unboosted servers?

**Comment by HexCodeFFF** [comment]
Probably just error out

**Comment by PortalRex** [comment]
Unfortunate, for now I'll have to leave it at 8. Thanks for the fast replies
