### ISSUE TITLE
add text bubble ($textbubble)

### ISSUE THREAD

**Issue by vxlkzients** [reticivis-net/mediaforge#83]
### Describe the feature you'd like

command to make media have those text speech bubbles on either the top of the media which have been a pretty recent trend

also if its possible maybe make the command have a variety of text bubbles with different styles?? would be awesome,,😀

### Anything Else

oh also transparent bg at the bubble or what place they call it so it matches with any discord theme👍

**Comment by reticivis-net** [comment]
done
