### ISSUE TITLE
'NoneType' object has no attribute 'delay_den'

### ISSUE THREAD

**Issue by espartiskills** [reticivis-net/mediaforge#85]
### Describe the bug

Bot halts, command inputted was "$demotivate |character development"

### Traceback

[traceback (1).txt](https://github.com/HexCodeFFF/mediaforge/files/8400555/traceback.1.txt)

### Expected Behavior

It to output a demotivational meme

### Steps To Reproduce

1) an input image
2) use "$demotivate"

**Comment by HexCodeFFF** [comment]
so mediaforge seems to be incorrectly reading the image as a video and trying to get its duration (which fails). can you send the image?

**Comment by reticivis-net** [comment]
closing until OP sends the image

**Comment by espartiskills** [comment]
yeah my bad, I assume I didn't have GitHub notification emails set up when I submitted the report like 2 years ago. 
I assume whatever the bug was got fixed when you redid a bunch of the code a year or so ago. apologies for the trouble

**Comment by reticivis-net** [comment]
> yeah my bad, I assume I didn't have GitHub notification emails set up when I submitted the report like 2 years ago. I assume whatever the bug was got fixed when you redid a bunch of the code a year or so ago. apologies for the trouble

nah I got the issue, I just was busy and not doing great mentally

I'm not 100% sure this issue is fixed since I don't think I actually touched much of the code that this issue is on, but maybe it is. if you could repro it then ill happily reopen it, if not then ill just leave it closed
